#ifndef DEFINITIONS_H
#define	DEFINITIONS_H
#include <cyg/hal/hal_arch.h>

//Stack and thread definitions
#define INIT_PRIORITY		19
#define LED_PRIORITY		18

//Stack thread sizes
#define INIT_STACK_SIZE		CYGNUM_HAL_STACK_SIZE_TYPICAL
#define LED_STACK_SIZE		CYGNUM_HAL_STACK_SIZE_MINIMUM

#define LCD_RS	CYGHWR_HAL_STM32_GPIO(B, 10, GPIO_OUT, 0, OPENDRAIN , NONE, 2MHZ)
#define LCD_RW	CYGHWR_HAL_STM32_GPIO(B, 14, GPIO_OUT, 0, OPENDRAIN , NONE, 2MHZ)
#define LCD_E	CYGHWR_HAL_STM32_GPIO(B, 12, GPIO_OUT, 0, PUSHPULL , NONE, 2MHZ)
#define LCD_DB0	CYGHWR_HAL_STM32_GPIO(E,  8, GPIO_OUT, 0, OPENDRAIN , NONE, 2MHZ)
#define LCD_DB1	CYGHWR_HAL_STM32_GPIO(E,  9, GPIO_OUT, 0, OPENDRAIN , NONE, 2MHZ)
#define LCD_DB2	CYGHWR_HAL_STM32_GPIO(E, 10, GPIO_OUT, 0, OPENDRAIN , NONE, 2MHZ)
#define LCD_DB3	CYGHWR_HAL_STM32_GPIO(E, 11, GPIO_OUT, 0, OPENDRAIN , NONE, 2MHZ)
#define LCD_DB4 CYGHWR_HAL_STM32_GPIO(E, 12, GPIO_OUT, 0, OPENDRAIN , NONE, 2MHZ)
#define LCD_DB5 CYGHWR_HAL_STM32_GPIO(E, 13, GPIO_OUT, 0, OPENDRAIN , NONE, 2MHZ)
#define LCD_DB6 CYGHWR_HAL_STM32_GPIO(E, 14, GPIO_OUT, 0, OPENDRAIN , NONE, 2MHZ)
#define LCD_DB7 CYGHWR_HAL_STM32_GPIO(E, 15, GPIO_OUT, 0, OPENDRAIN , NONE, 2MHZ)

#endif	/* DEFINITIONS_H */

